runtime: php55
api_version: 1
threadsafe: false


handlers:
  - url: /user_guide/
    static_files: user_guide/index.html
    upload: user_guide/index.html

  - url: /user_guide/(.*)
    static_files: user_guide/\1
    upload: user_guide/(.*)

  - url: /static/(.*)
    static_files: static/\1
    upload: static/(.*)

  - url: /assets/(.*)
    static_files: assets/\1
    upload: assets/(.*)

  - url: /
    script: index.php

  - url: /(.+)
    script: index.php

env_variables:
  MYSQL_USER: touristix_web
  MYSQL_PASSWORD: 4bandaaceh
  CI_ENV: production
  MIDTRANS_SERVER_KEY: SB-Mid-server-U1JOPy64wQFjCV67_vA_p8nu
  MIDTRANS_PRODUCTION: true

skip_files:
  - ^(.git/.*)
  - ^(assets/.*)
